language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t engldv01/docker-react -f Dockerfile.dev .
  

script:
  - docker run -e CI=true engldv01/docker-react npm run test